### ISSUE TITLE
Bug: enqueue form doesn't generate q card

### ISSUE THREAD

**Issue by athelia** [KatrinaHuberJuma/q-cards#1]
Expected behavior: As a student, pressing "submit" to successfully send the enqueue form should cause a card to appear when the window closes

Actual behavior: Although the data is submitted to the server (reloading shows the new card) and an alert pops up, the card does not appear.

**Comment by KatrinaHuberJuma** [comment]
very sad student view
<img width="1401" alt="Screen Shot 2021-06-09 at 6 27 34 PM" src="https://user-images.githubusercontent.com/13302399/121450674-08acac00-c951-11eb-97aa-579ab7c71b05.png">

all the excitement happens _behind the scenes_
![Screen Shot 2021-06-09 at 6 29 00 PM](https://user-images.githubusercontent.com/13302399/121450638-ffbbda80-c950-11eb-9717-c072e5238a08.png)
